name: Check for Upstream Updates and Send Email

on:
  schedule:
    - cron: '0 10 * * 0'  # 每周天下午18点中国时间运行
  workflow_dispatch:  # 手动触发

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Upstream Repository
        run: |
          git remote add upstream https://github.com/hehonghui/awesome-english-ebooks.git
          git fetch upstream

      - name: Check for New Commits
        id: check_updates
        run: |
          git fetch upstream
          NEW_COMMITS=$(git rev-list HEAD..upstream/main --count)
          echo "::set-output name=new_commits::$NEW_COMMITS"
      
      - name: Sync with Upstream
        if: steps.check_updates.outputs.new_commits != '0'
        run: |
          git merge upstream/master
          git push origin master
      
      - name: Send Email if Updates Found
        if: steps.check_updates.outputs.new_commits != '0'
        uses: devellany/send-mail@v1.0.2
        with:
          host: 'smtp.qq.com' # qq邮箱主机
          port: 465 # SMTP 端口 或者587
          account: ${{ secrets.EMAIL }}  # 邮箱地址，最好用GitHub Secrets管理
          password: ${{ secrets.APP_PASSWORD }}  # 邮箱密码，强烈建议使用GitHub Secrets
          sender: GITHUB  # 发件人的名字
          from: ${{ secrets.EMAIL }}  # 发件人的邮箱地址
          to: ${{ secrets.TARGET_EMAIL }}  # 收件人的邮箱地址，可以多个邮箱，用逗号分隔
          subject: "Repository Updates"  # 邮件主题
          body: "Found new updates in the repository."  # 邮件正文
